version: '3'


services:

  traefik:
    image: traefik:v2.5
    restart: always

    command:
      # - "--log.level=DEBUG"
      # - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"

      # - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http"
      - "--certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/.letsencrypt/acme.json"

    volumes:
      - "./docker/traefik/mount/.letsencrypt:/.letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    networks:
      - traefik_network

    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080"


  nextcloud_db:
    image: postgres:13.1-alpine
    restart: always

    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${NEXTCLOUD_DATABASE_USER}", "-d", "${NEXTCLOUD_DATABASE_NAME}" ]
      interval: 15s
      timeout: 3s
      retries: 8

    environment:
      - POSTGRES_DB=${NEXTCLOUD_DATABASE_NAME}
      - POSTGRES_USER=${NEXTCLOUD_DATABASE_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_DATABASE_PASSWORD}

    volumes:
      - ./docker/nextcloud_db/mount/var/lib/postgresql/data:/var/lib/postgresql/data

    networks:
      - internal_network


  nextcloud_cache:
    image: redis:6-alpine
    restart: always

    networks:
      - internal_network


  nextcloud:
    image: nextcloud:22-apache
    restart: always

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"

      - "traefik.http.routers.nextcloud.entrypoints=http"
      - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_HOST}`)"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud@docker"
      - "traefik.http.middlewares.nextcloud.redirectscheme.scheme=https"

      - "traefik.http.routers.nextcloud_https.entrypoints=https"
      - "traefik.http.routers.nextcloud_https.rule=Host(`${NEXTCLOUD_HOST}`)"
      - "traefik.http.routers.nextcloud_https.tls.certresolver=letsencrypt"

    environment:
      - POSTGRES_HOST=nextcloud_db
      - POSTGRES_DB=${NEXTCLOUD_DATABASE_NAME}
      - POSTGRES_USER=${NEXTCLOUD_DATABASE_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_DATABASE_PASSWORD}

      - REDIS_HOST=nextcloud_cache

      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_HOST}

    volumes:
      - ./docker/nextcloud/mount/var/www/html:/var/www/html

    networks:
      - traefik_network
      - internal_network

    depends_on:
      - nextcloud_db
      - nextcloud_cache
      - traefik


networks:
  traefik_network:
    # Need to explicitly set the name, so that docker-compose does not prefix it.
    name: traefik_network
  internal_network:
