version: '3.3'


services:


  mattermost_db:
    image: postgres:14-alpine
    restart: unless-stopped

    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    tmpfs:
      - /tmp
      - /var/run/postgresql

    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${MATTERMOST_DATABASE_USER}", "-d", "${MATTERMOST_DATABASE_NAME}" ]

    environment:
      TZ: ${TZ}

      POSTGRES_DB: ${MATTERMOST_DATABASE_NAME}
      POSTGRES_USER: ${MATTERMOST_DATABASE_USER}
      POSTGRES_PASSWORD: ${MATTERMOST_DATABASE_PASSWORD}

    volumes:
      - mattermost_db:/var/lib/postgresql/data

    networks:
      - mattermost_network


  mattermost:
    image: mattermost/mattermost-team-edition:release-7.5
    restart: unless-stopped

    security_opt:
      - no-new-privileges:true
    pids_limit: 200
    tmpfs:
      - /tmp

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"

      - "traefik.http.routers.mattermost-https.entrypoints=https"
      - "traefik.http.routers.mattermost-https.rule=Host(`${MATTERMOST_DOMAIN}`)"
      - "traefik.http.routers.mattermost-https.tls.certresolver=letsencrypt"

      - "traefik.http.middlewares.mattermost-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.mattermost-https.redirectscheme.permanent=true"

      - "traefik.http.routers.mattermost-http.entrypoints=http"
      - "traefik.http.routers.mattermost-http.rule=Host(`${MATTERMOST_DOMAIN}`)"
      - "traefik.http.routers.mattermost-http.middlewares=mattermost-https"

    environment:
      TZ: ${TZ}

      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SQLSETTINGS_DATASOURCE: postgres://${MATTERMOST_DATABASE_USER}:${MATTERMOST_DATABASE_PASSWORD}@mattermost_db:5432/${MATTERMOST_DATABASE_NAME}?sslmode=disable&connect_timeout=10

      MM_BLEVESETTINGS_INDEXDIR: /mattermost/bleve-indexes

      MM_SERVICESETTINGS_SITEURL: https://${MATTERMOST_DOMAIN}

    volumes:
      - MATTERMOST_CONFIG_PATH:/mattermost/config
      - MATTERMOST_DATA_PATH:/mattermost/data
      - MATTERMOST_LOGS_PATH:/mattermost/logs
      - MATTERMOST_PLUGINS_PATH:/mattermost/plugins
      - MATTERMOST_CLIENT_PLUGINS_PATH:/mattermost/client/plugins
      - MATTERMOST_BLEVE_INDEXES_PATH:/mattermost/bleve-indexes

    networks:
      - mattermost_network
      - traefik_network

    depends_on:
      - mattermost_db


volumes:
  mattermost_db:
  MATTERMOST_CONFIG_PATH:
  MATTERMOST_DATA_PATH:
  MATTERMOST_LOGS_PATH:
  MATTERMOST_PLUGINS_PATH:
  MATTERMOST_CLIENT_PLUGINS_PATH:
  MATTERMOST_BLEVE_INDEXES_PATH:


networks:
  mattermost_network:
  traefik_network:
    external: true
