version: '3.3'


services:


  database:
    image: postgres:${DATABASE_TAG}
    restart: unless-stopped

    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    tmpfs:
      - /tmp
      - /var/run/postgresql

    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DATABASE_USER}", "-d", "${DATABASE_NAME}" ]

    labels:
      com.centurylinklabs.watchtower.enable: "true"

    environment:
      TZ: ${TZ}

      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

    volumes:
      - database:/var/lib/postgresql/data


  mattermost:
    image: mattermost/mattermost-team-edition:${TAG}
    restart: unless-stopped

    security_opt:
      - no-new-privileges:true
    pids_limit: 200
    tmpfs:
      - /tmp

    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik_network"

      traefik.http.routers.mattermost-https.entrypoints: "https"
      traefik.http.routers.mattermost-https.rule: "Host(`${DOMAIN}`)"
      traefik.http.routers.mattermost-https.tls.certresolver: "letsencrypt"

      traefik.http.middlewares.mattermost-https.redirectscheme.scheme: "https"
      traefik.http.middlewares.mattermost-https.redirectscheme.permanent: "true"

      traefik.http.routers.mattermost-http.entrypoints: "http"
      traefik.http.routers.mattermost-http.rule: "Host(`${DOMAIN}`)"
      traefik.http.routers.mattermost-http.middlewares: "mattermost-https"

      com.centurylinklabs.watchtower.enable: "true"

    environment:
      TZ: ${TZ}

      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SQLSETTINGS_DATASOURCE: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@database:5432/${DATABASE_NAME}?sslmode=disable&connect_timeout=10

      MM_BLEVESETTINGS_INDEXDIR: /mattermost/bleve-indexes

      MM_SERVICESETTINGS_SITEURL: https://${DOMAIN}

    volumes:
      - ${DATA_PATH}/config:/mattermost/config
      - ${DATA_PATH}/data:/mattermost/data
      - logs:/mattermost/logs
      - plugins:/mattermost/plugins
      - client-plugins:/mattermost/client/plugins
      - bleve-indexes:/mattermost/bleve-indexes

    networks:
      - default
      - traefik_network

    depends_on:
      - database


volumes:
  database:
  logs:
  plugins:
  client-plugins:
  bleve-indexes:


networks:
  traefik_network:
    external: true
